### ISSUE TITLE
Can I use code in WorldBot AMP

### ISSUE THREAD

**Issue by JupeOwl** [Sea-Pickle/worldbox_map_creation#1]
Heya!

I'm jupeowl in discord, worldbox server administrator. I'd love to use this code to replace my current crappy code in Worldbot AMP and make stuff actually work if you're fine with it. I'd of course add credit to you

**Comment by JupeOwl** [comment]
btw sorry for the odd way of getting in touch. Didn't know how to reach you. You can dm or ping me in discord if you'd like

**Comment by gloop-6** [comment]
go ahead, sure
