### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by 100288840** [Sea-Pickle/worldbox_map_creation#2]
This error occurs even with the included png files for testing purposes.

**Comment by gloop-6** [comment]
can you give the full error? I can't do much without it

**Comment by 100288840** [comment]
```
Traceback (most recent call last):
  File "worldbox_map_creation-main\create_map_from_image.py", line 284, in <module>
    im2,map_width,map_height = convert_image(im)
  File "\worldbox_map_creation-main\create_map_from_image.py", line 204, in convert_image
    image = image.resize(image_scale)
  File "\Python310\lib\site-packages\PIL\Image.py", line 2155, in resize
    size = tuple(size)
TypeError: 'int' object is not iterable
```
my python version is  3.10.4, and Pillow version is 9.5.0

**Comment by gloop-6** [comment]
Oh, that’s due to a change in config, in config.json, set image_scale to two numbers in brackets (i.e [100,100]) or delete the file and run the script again to regenerate it

I plan on reworking it again in the future to prevent this being an issue

**Comment by 100288840** [comment]
> Oh, that’s due to a change in config, in config.json, set image_scale to two numbers in brackets (i.e [100,100]) or delete the file and run the script again to regenerate it
> 
> I plan on reworking it again in the future to prevent this being an issue

It works!
